#!/usr/bin/env python3
"""
Generate SQL seed data for Football Modules 2 & 3
"""

import json
import os

# UUIDs for modules 2 and 3
MODULE_2_ID = "00000000-0000-0000-0000-000000000002"
MODULE_3_ID = "00000000-0000-0000-0000-000000000003"
# Use the actual football sport ID from your database
FOOTBALL_SPORT_ID = "0105433b-5bdd-4093-b6b1-157a0c3c515e"

def get_lesson_id(module_num, lesson_index):
    """Generate lesson UUID: 0000000M-0000-0000-0000-0000000000LL"""
    return f"0000000{module_num}-0000-0000-0000-0000000000{lesson_index:02d}"

def get_item_id(module_num, lesson_index, item_index):
    """Generate item UUID: 0000000M-00LL-0000-0000-0000000000II"""
    return f"0000000{module_num}-00{lesson_index:02d}-0000-0000-0000000000{item_index:02d}"

def get_variant_id(module_num, lesson_index, item_index):
    """Generate variant UUID: 0000000M-00LL-00II-0000-000000000001"""
    return f"0000000{module_num}-00{lesson_index:02d}-00{item_index:02d}-0000-000000000001"

def escape_sql_string(s):
    """Escape single quotes for SQL"""
    if s is None:
        return "NULL"
    return s.replace("'", "''")

def generate_sql():
    sql_lines = []
    
    # Header
    sql_lines.append("-- Football Modules 2 & 3 Seed Data")
    sql_lines.append("-- Generated by generate_modules_2_3_seed.py")
    sql_lines.append("")
    
    AUTHOR_ID_SQL = "(SELECT id FROM users LIMIT 1)"

    # Module 2: Offensive Concepts
    sql_lines.append("-- Insert Module 2: Offensive Concepts")
    sql_lines.append(f"""INSERT INTO modules (id, sport_id, title, description, order_index, min_level, max_level, xp_reward, created_at, updated_at)
VALUES (
  '{MODULE_2_ID}',
  '{FOOTBALL_SPORT_ID}',
  'Offensive Concepts',
  'Master offensive formations, routes, and strategies',
  2,
  2,
  3,
  0,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  min_level = EXCLUDED.min_level,
  max_level = EXCLUDED.max_level,
  xp_reward = EXCLUDED.xp_reward,
  updated_at = NOW();
""")
    
    # Module 3: Defensive Concepts
    sql_lines.append("-- Insert Module 3: Defensive Concepts")
    sql_lines.append(f"""INSERT INTO modules (id, sport_id, title, description, order_index, min_level, max_level, xp_reward, created_at, updated_at)
VALUES (
  '{MODULE_3_ID}',
  '{FOOTBALL_SPORT_ID}',
  'Defensive Concepts',
  'Master defensive formations, coverages, and strategies',
  3,
  3,
  4,
  0,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  min_level = EXCLUDED.min_level,
  max_level = EXCLUDED.max_level,
  xp_reward = EXCLUDED.xp_reward,
  updated_at = NOW();
""")
    
    # Process Module 2 content files
    module_2_files = [
        'content/module2_offensive_concepts_part1.json',
        'content/module2_offensive_concepts_part2.json'
    ]
    
    lesson_counter = 1
    for file_path in module_2_files:
        with open(file_path, 'r') as f:
            data = json.load(f)
            
        # Get lessons from either 'module' or 'additional_lessons'
        if 'module' in data:
            lessons = data['module']['lessons']
        elif 'additional_lessons' in data:
            lessons = data['additional_lessons']
        else:
            continue
            
        for lesson in lessons:
            lesson_id = get_lesson_id(2, lesson_counter)
            
            sql_lines.append(f"-- Module 2, Lesson {lesson_counter}: {lesson['title']}")
            sql_lines.append(f"""INSERT INTO lessons (id, module_id, title, description, order_index, est_minutes, xp_award, created_at, updated_at)
VALUES (
  '{lesson_id}',
  '{MODULE_2_ID}',
  '{escape_sql_string(lesson['title'])}',
  '{escape_sql_string(lesson['description'])}',
  {lesson['order_index']},
  {lesson['est_minutes']},
  {lesson['xp_award']},
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  est_minutes = EXCLUDED.est_minutes,
  xp_award = EXCLUDED.xp_award,
  updated_at = NOW();
""")
            
            # Process items
            item_counter = 1
            for item in lesson['items']:
                item_id = get_item_id(2, lesson_counter, item_counter)
                variant_id = get_variant_id(2, lesson_counter, item_counter)
                
                variant = item['variant']
                options_json = json.dumps(variant['options_json']).replace("'", "''")
                correct_answer_json = json.dumps(variant['correct_answer_json']).replace("'", "''")
                
                # Construct answer_schema_json
                schema = {
                    "type": item['type'],
                    "options": variant['options_json'],
                    "correct": variant['correct_answer_json']['index']
                }
                schema_json = json.dumps(schema).replace("'", "''")

                sql_lines.append(f"""INSERT INTO items (id, lesson_id, type, base_prompt, answer_schema_json, difficulty, status, author_id, created_at, updated_at)
VALUES (
  '{item_id}',
  '{lesson_id}',
  '{item['type']}',
  '{escape_sql_string(item['base_prompt'])}',
  '{schema_json}'::jsonb,
  {item['difficulty']},
  'live',
  {AUTHOR_ID_SQL},
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  base_prompt = EXCLUDED.base_prompt,
  answer_schema_json = EXCLUDED.answer_schema_json,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  updated_at = NOW();
""")
                
                sql_lines.append(f"""INSERT INTO item_variants (id, item_id, version, prompt_richtext, options_json, correct_answer_json, explanation_richtext, active, created_at, updated_at)
VALUES (
  '{variant_id}',
  '{item_id}',
  1,
  '{escape_sql_string(variant['prompt_richtext'])}',
  '{options_json}',
  '{correct_answer_json}',
  '{escape_sql_string(variant['explanation_richtext'])}',
  true,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  prompt_richtext = EXCLUDED.prompt_richtext,
  options_json = EXCLUDED.options_json,
  correct_answer_json = EXCLUDED.correct_answer_json,
  explanation_richtext = EXCLUDED.explanation_richtext,
  active = EXCLUDED.active,
  updated_at = NOW();
""")
                
                item_counter += 1
            
            lesson_counter += 1
    
    # Process Module 3 content files
    module_3_files = [
        'content/module3_defensive_concepts_part1.json',
        'content/module3_defensive_concepts_part2.json'
    ]
    
    lesson_counter = 1
    for file_path in module_3_files:
        with open(file_path, 'r') as f:
            data = json.load(f)
            
        # Get lessons from either 'module' or 'additional_lessons'
        if 'module' in data:
            lessons = data['module']['lessons']
        elif 'additional_lessons' in data:
            lessons = data['additional_lessons']
        else:
            continue
            
        for lesson in lessons:
            lesson_id = get_lesson_id(3, lesson_counter)
            
            sql_lines.append(f"-- Module 3, Lesson {lesson_counter}: {lesson['title']}")
            sql_lines.append(f"""INSERT INTO lessons (id, module_id, title, description, order_index, est_minutes, xp_award, created_at, updated_at)
VALUES (
  '{lesson_id}',
  '{MODULE_3_ID}',
  '{escape_sql_string(lesson['title'])}',
  '{escape_sql_string(lesson['description'])}',
  {lesson['order_index']},
  {lesson['est_minutes']},
  {lesson['xp_award']},
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index,
  est_minutes = EXCLUDED.est_minutes,
  xp_award = EXCLUDED.xp_award,
  updated_at = NOW();
""")
            
            # Process items
            item_counter = 1
            for item in lesson['items']:
                item_id = get_item_id(3, lesson_counter, item_counter)
                variant_id = get_variant_id(3, lesson_counter, item_counter)
                
                variant = item['variant']
                options_json = json.dumps(variant['options_json']).replace("'", "''")
                correct_answer_json = json.dumps(variant['correct_answer_json']).replace("'", "''")
                
                # Construct answer_schema_json
                schema = {
                    "type": item['type'],
                    "options": variant['options_json'],
                    "correct": variant['correct_answer_json']['index']
                }
                schema_json = json.dumps(schema).replace("'", "''")
                
                sql_lines.append(f"""INSERT INTO items (id, lesson_id, type, base_prompt, answer_schema_json, difficulty, status, author_id, created_at, updated_at)
VALUES (
  '{item_id}',
  '{lesson_id}',
  '{item['type']}',
  '{escape_sql_string(item['base_prompt'])}',
  '{schema_json}'::jsonb,
  {item['difficulty']},
  'live',
  {AUTHOR_ID_SQL},
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  base_prompt = EXCLUDED.base_prompt,
  answer_schema_json = EXCLUDED.answer_schema_json,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  updated_at = NOW();
""")
                
                sql_lines.append(f"""INSERT INTO item_variants (id, item_id, version, prompt_richtext, options_json, correct_answer_json, explanation_richtext, active, created_at, updated_at)
VALUES (
  '{variant_id}',
  '{item_id}',
  1,
  '{escape_sql_string(variant['prompt_richtext'])}',
  '{options_json}',
  '{correct_answer_json}',
  '{escape_sql_string(variant['explanation_richtext'])}',
  true,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  prompt_richtext = EXCLUDED.prompt_richtext,
  options_json = EXCLUDED.options_json,
  correct_answer_json = EXCLUDED.correct_answer_json,
  explanation_richtext = EXCLUDED.explanation_richtext,
  active = EXCLUDED.active,
  updated_at = NOW();
""")
                
                item_counter += 1
            
            lesson_counter += 1
    
    return '\n'.join(sql_lines)

if __name__ == '__main__':
    sql = generate_sql()
    
    # Write to file
    output_file = 'supabase/seed_modules_2_3.sql'
    with open(output_file, 'w') as f:
        f.write(sql)
    
    print(f"Generated {output_file}")
    print("Run this SQL in your Supabase SQL editor to seed Modules 2 & 3")
